/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as GiftHampersRouteImport } from './routes/gift-hampers'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as OrderTrackRouteImport } from './routes/order-track'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as RefurbishedRouteImport } from './routes/refurbished'
import { Route as RepairRouteImport } from './routes/repair'
import { Route as ServicesRouteImport } from './routes/services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GiftHampersRoute = GiftHampersRouteImport.update({
  id: '/gift-hampers',
  path: '/gift-hampers',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTrackRoute = OrderTrackRouteImport.update({
  id: '/order-track',
  path: '/order-track',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const RefurbishedRoute = RefurbishedRouteImport.update({
  id: '/refurbished',
  path: '/refurbished',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairRoute = RepairRouteImport.update({
  id: '/repair',
  path: '/repair',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gift-hampers': typeof GiftHampersRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/order-track': typeof OrderTrackRoute
  '/products': typeof ProductsRoute
  '/refurbished': typeof RefurbishedRoute
  '/repair': typeof RepairRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gift-hampers': typeof GiftHampersRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/order-track': typeof OrderTrackRoute
  '/products': typeof ProductsRoute
  '/refurbished': typeof RefurbishedRoute
  '/repair': typeof RepairRoute
  '/services': typeof ServicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/gift-hampers': typeof GiftHampersRoute
  '/offers': typeof OffersRoute
  '/order-success': typeof OrderSuccessRoute
  '/order-track': typeof OrderTrackRoute
  '/products': typeof ProductsRoute
  '/refurbished': typeof RefurbishedRoute
  '/repair': typeof RepairRoute
  '/services': typeof ServicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/gift-hampers'
    | '/offers'
    | '/order-success'
    | '/order-track'
    | '/products'
    | '/refurbished'
    | '/repair'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/gift-hampers'
    | '/offers'
    | '/order-success'
    | '/order-track'
    | '/products'
    | '/refurbished'
    | '/repair'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/gallery'
    | '/gift-hampers'
    | '/offers'
    | '/order-success'
    | '/order-track'
    | '/products'
    | '/refurbished'
    | '/repair'
    | '/services'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  GiftHampersRoute: typeof GiftHampersRoute
  OffersRoute: typeof OffersRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OrderTrackRoute: typeof OrderTrackRoute
  ProductsRoute: typeof ProductsRoute
  RefurbishedRoute: typeof RefurbishedRoute
  RepairRoute: typeof RepairRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gift-hampers': {
      id: '/gift-hampers'
      path: '/gift-hampers'
      fullPath: '/gift-hampers'
      preLoaderRoute: typeof GiftHampersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-track': {
      id: '/order-track'
      path: '/order-track'
      fullPath: '/order-track'
      preLoaderRoute: typeof OrderTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refurbished': {
      id: '/refurbished'
      path: '/refurbished'
      fullPath: '/refurbished'
      preLoaderRoute: typeof RefurbishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repair': {
      id: '/repair'
      path: '/repair'
      fullPath: '/repair'
      preLoaderRoute: typeof RepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  GiftHampersRoute: GiftHampersRoute,
  OffersRoute: OffersRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OrderTrackRoute: OrderTrackRoute,
  ProductsRoute: ProductsRoute,
  RefurbishedRoute: RefurbishedRoute,
  RepairRoute: RepairRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
